### ISSUE TITLE
npm start报错。

### ISSUE THREAD

**Issue by wangfei-1022** [liu-dongyu/react-begin#1]
$ npm start

> react-begin@1.0.0 start d:\whyfind_github\react-begin
> NODE_ENV=dev webpack-dev-server --config webpack.config.babel.js --watch-poll --inline --hot

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

是要做什么特殊处理吗。

**Comment by liu-dongyu** [comment]
没什么特别的处理. `npm install` 成功之后应该就可以了。使用什么系统呢， windows吗?

**Comment by wangfei-1022** [comment]
嗯是的啊 windows

**Comment by liu-dongyu** [comment]
我不用window做开发的，因为总是有一些奇奇怪怪的兼容性问题。看看下面的链接能不能帮到你？

http://stackoverflow.com/questions/11928013/node-env-is-not-recognized-as-an-internal-or-external-command-operable-comman

https://github.com/AngularClass/angular2-webpack-starter/issues/54

https://segmentfault.com/q/1010000004257007

**Comment by wangfei-1022** [comment]
好的阿。谢谢阿。我去看看。

**Comment by wangfei-1022** [comment]
好了。应该就是windows的兼容问题了。package.json 的start的对应改成这样就好了。
"start": "SET NODE_ENV=dev& webpack-dev-server --config webpack.config.babel.js --watch-poll --inline --hot"
